# Generated by Django 5.0.7 on 2024-07-22 02:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trailers', '0002_movie_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='trailer_url',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='video'),
        ),
    ]
